@startuml Diagrama de Clases TP
    title "Diagrama de Clases\nTrabajo Práctico"
    
     enum EstadoPedido{
        EN_CONSTRUCCION
        CONFIRMADO
        FACTURADO
    }

    enum Categoria{
        ENTRADA
        PLATO_PRINCIPAL
        BEBIDA
        POSTRE
    }

    enum EstadoItem{
        PENDIENTE
        EN_PREPARACION
        LISTO
    }
    enum TipoTarjeta{
        DEBITO
        CREDITO
    }
    '-------------Restaurante-Sistema-----------------------
    class Restaurante{
        -menu:Menu
        -cocinas:Cocina[]
        -descuentos:Descuento[]
        -historialPedidos:Pedido[]

        +registrarPedido(pedido:Pedido):void
        +confirmarPedido(pedido:Pedido):void
        +facturarPedido(pedido:Pedido):void
        +consultarHistorial():void
    }
    Restaurante *-- Menu
    Restaurante *-- Cocina
    Restaurante o-- Pedido
    Restaurante ..|> Descuento



    '------------------ PEDIDOS -------------------------

    abstract class Pedido {
        -id_pedido: number
        -items: ItemPedido[]
        -estado: EstadoPedido
        -medioPago:MedioPago
        -totalCobrado:number        


        +agregarItem(item:ItemPedido):void
        +sacarItem(item:ItemPedido):void
        +calcularPrecioFinal(): number
        +setEstado(estado: EstadoPedido): void
        +getEstado(): EstadoPedido
        +deshacerUltimaModificacion():void
        +estaListoParaFacturar():boolean
        +facturar():void
        +calcularTotalCobrar():number

    }

    class PedidoSalon {
        -nMesa: number
    }

    class PedidoRetirar {
        -horario: number
    }

    class PedidoEnvio {
        -direccion: string
        -costoEnvio: number
    }

    PedidoSalon -u-|> Pedido
    PedidoRetirar -u-|> Pedido
    PedidoEnvio -u-|> Pedido

    Pedido *-- ItemPedido


    '------------ MENU / PRODUCTOS -------------

    class Menu {
        -productos: ProductoIndividual[]
        -combos: Combo[]

        +agregarProducto(producto:Producto):void
        +sacarProducto(producto:Producto):void
        +getProductoPorCategoria(categoria:Categoria):Producto[]
    }

    interface Producto {

        +getPrecio(): number
    }

    class ProductoIndividual {
        -nombre: string
        -precio: number
        -categoria: Categoria

        +getPrecio(): number
        +getCategorias(): Categoria[]
    }

    class Combo  {
        -productos: ProductoIndividual[]
        -beneficio: Beneficio

        +getPrecio(): number
        +getCategorias():Categoria[]
    }

    ProductoIndividual ..|> Producto
    Menu *-- ProductoIndividual
    Menu *-- Combo
    Combo *-- ProductoIndividual
    Combo ..|> Producto


    '------------------ BENEFICIOS -----------------

    interface Beneficio {
        +calcularBeneficio(precioBase: number): number
    }

    class BeneficioPorcentual {
        -porcentaje: number
    }

    class BeneficioPrecioFijo {
        -precio: number
    }

    BeneficioPorcentual ..|> Beneficio
    BeneficioPrecioFijo ..|> Beneficio

    Combo ..|> Beneficio


    '------------------ ITEMS -----------------

    class ItemPedido {
        -producto: Producto
        -estado: EstadoItem
        -cantidad: number
        

        +marcarEnPreparacion():void
        +marcarListo():void
        +puedeModificarse():boolean
    }



    '--------------------- COCINA ----------------------

    abstract class Cocina {
        -nombre:string
        -items: ItemPedido[]

        +recibirItem(item: ItemPedido): void
        +procesarSiguiente(): void
    }

    class Parrilla{}
    class CocinaDulce{}
    class CocinaFria{}
    class Barra{}

    Parrilla --|> Cocina
    CocinaDulce --|> Cocina
    CocinaFria --|> Cocina
    Barra --|> Cocina
    Cocina *-- Pedido
    '------------------- MedioPago ------------------------
    interface MedioPago{
        +cobrar()
    }
    class Efectivo{}
    abstract class Tarjeta{
        -numero:string
        -tipo:TipoTarjeta
    }
    class TarjetaDebito{}
    class TarjetaCredito{}
    class BilleteraVirtual{}
    Efectivo ..|> MedioPago
    Tarjeta ..|> MedioPago
    BilleteraVirtual ..|> MedioPago

    TarjetaDebito --|> Tarjeta
    TarjetaCredito --|> Tarjeta

    interface Descuento{
        +calcularDescuento(pedido:Pedido):number
    }
    class DescuentoEfectivo{
        -porcentaje:number
    }
    class DescuentoDia{
        -dia:string
        -porcentaje:number
    }
    DescuentoEfectivo ..|> Descuento
    DescuentoDia ..|> Descuento

    '-------------------- Historial------------------------
    class HistorialPedido{
        -pedidosFinalizados:Map<number, Pedido>
        +agregarPedido(pedido:Pedido):void
        +consultarPedidos():Pedido[]
    }
    HistorialPedido o-- Pedido
    HistorialPedido "1" --> "0..*" Pedido
    'Un pedido contiene exactamente Un registro en historial de Pedidos
    'HistorialPedido puede contener 0 o muchos pedidos.
@enduml