@startuml Diagrama de Clases TP
    title "Diagrama de Clases\nTrabajo Práctico"
    
     enum EstadoPedido{
        EN_CONSTRUCCION
        CONFIRMADO
        FACTURADO
    }

    enum Categoria{
        ENTRADA
        PLATO_PRINCIPAL
        BEBIDA
        POSTRE
    }

    enum EstadoItem{
        PENDIENTE
        EN_PREPARACION
        LISTO
    }
    enum TipoTarjeta{
        DEBITO
        CREDITO
    }
    '-------------Restaurante-Sistema-----------------------

    class Restaurante{
        -menu:Menu
        -cocinas:Cocina[]
        -gestorPedidos:GestorPedidos
        -gestorPagos:GestorPagos
    }

    '------------------ PEDIDOS -------------------------

    abstract class Pedido {
        -id_pedido: number
        -items: ItemPedido[]
        -estado: EstadoPedido
        -precioFinal: number

        +puedeModificarse():boolean
        +agregarItem(item:ItemIndividual):void
        +sacarItem(item:ItemIndividual):void
        +setEstado(estado: EstadoPedido): void
        +deshacerUltimaModificacion():void
        +estaListoParaFacturar():boolean
        +facturar():void
        +calcularTotalCobrar():number

    }

    class PedidoSalon {
        -nMesa: number
    }

    class PedidoRetirar {
        -horario: number
    }

    class PedidoEnvio {
        -direccion: string
        -costoEnvio: number
    }

    '------------ MENU / PRODUCTOS -------------

    class Menu {
        -entradas: itemIndividual[]
        -platosPrincipales: itemIndividual[]
        -bebidas: itemIndividual[]
        -postres: itemIndividual[]
        -combos: Combo[]

        +agregarProducto(producto:Producto):void
        +sacarProducto(producto:Producto):void
        +getProductoPorCategoria(categoria:Categoria):Producto[]
    }

    interface Producto {

        +getPrecio(): number
    }

    class ItemIndividual {
        -nombre: string
        -precio: number
        -estado: EstadoItem
        -categoria: Categoria
        -cantidad: number

        +getPrecio(): number
        +getCategoria(): Categoria
        +marcarEnPreparacion():void
        +marcarListo():void
    }

    class Combo {
        -productos: ItemIndividual[]
    }

    '------------------ BENEFICIO -----------------

    interface Beneficio {
        +calcularBeneficio(precioBase: number): number
    }

    '--------------------- COCINA ----------------------

    abstract class Cocina {
        -nombre:string
        -items: ItemIndividual[]

        +recibirItem(item: ItemIndividual): void
        +cocinarItem(item: itemIndividual): void
    }

    class Parrilla{}
    class CocinaDulce{}
    class CocinaFria{}
    class Barra{}

    '------------------ GESTOR_PAGOS -------------------------

    class GestorPagos {
        -medioPago: MedioPago

        +Cobrar(pedido : Pedido): Factura
    }

    '------------------- MedioPago ------------------------

    abstract class MedioPago{
        
        +Pagar()
    }

    class Efectivo {}

    class Tarjeta{
        -numero:string
        -tipo:TipoTarjeta
    }
    
    class BilleteraVirtual{}

    interface Descuento{
        +calcularDescuento(pedido:Pedido):number
    }

    class DescuentoDia{
        -dia:string
        -porcentaje:number
    }

    '-------------------- Gestor de Pedidos ------------------------

    class GestorPedidos{
        -pedidosFinalizados:Map<number, Pedido>

        +consultarHistorial():void
        +crearPedido() : Pedido
        +confirmarPedido(pedido:Pedido):void
        +registrarPedido(pedido:Pedido):void
    }

    '-------------------- RELACIONES ------------------------

'RESTAURANTE

    Restaurante *-r- Menu
    Restaurante *-- Cocina
    'Restaurante o-- Pedido
    Restaurante *-d- GestorPedidos
    Restaurante *--l- GestorPagos
    'Restaurante ..|> Descuento

'PEDIDOS

    Pedido <|-d- PedidoSalon
    Pedido <|-d- PedidoRetirar
    Pedido <|-d- PedidoEnvio
    Pedido -r-* ItemIndividual
    Pedido --* Cocina
    Pedido ..|> Producto

'MENU

    ItemIndividual ..|> Producto
    Menu *-- ItemIndividual
    Menu *-- Combo
    Combo *-- ItemIndividual
    Combo ..|> Producto
    Combo ..|> Beneficio

'COCINA

    Parrilla -u-|> Cocina
    CocinaDulce -u-|> Cocina
    CocinaFria -u-|> Cocina
    Barra -u-|> Cocina

'GESTOR DE PAGOS

    GestorPagos -l-* MedioPago
    GestorPagos --o DescuentoDia

'MEDIOS DE PAGO

    Efectivo -u-|> MedioPago
    Tarjeta -r-|> MedioPago
    BilleteraVirtual -d-|> MedioPago
    Efectivo .d.|> Descuento

'DESCUENTOS

    DescuentoDia ..|> Descuento

'GESTOR DE PEDIDOS

    'HistorialPedido o-- Pedido
    GestorPedidos *-- Pedido
    'Un pedido contiene exactamente Un registro en historial de Pedidos
    'HistorialPedido puede contener 0 o muchos pedidos.

@enduml